"""empty message

Revision ID: 384a8bbae314
Revises: 3e382b2d70be
Create Date: 2016-09-23 21:03:05.959507

"""

# revision identifiers, used by Alembic.
revision = '384a8bbae314'
down_revision = '3e382b2d70be'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('description', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'description')
    ### end Alembic commands ###
